### ISSUE TITLE
refactoring package

### ISSUE THREAD

**Issue by jays-notebook** [kim-kwanghoon/portfolio#2]
- recommend using this package rules
  - `domain name` reverse
    - example
      - domain : `mail.google.com`
      - package : `com.google.mail`
  - or `group id` + `artifact id`
    - example : `example.kwanghoon.portfolio`
- do not use pointless package name (naver_login)
- do not use an irrelevant package name (org.spring)

**Comment by kim-kwanghoon** [comment]
브렌치를 통한 리패키징 완료!
issue solution / Problem solving / Check completed
